eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
#  aggregator:
#    clusterConfig: MS-HELLO
  app-config: ms-hello,ms-world
  clusterNameExpression: "'default'"
