server:
  port: 9002


security:
  oauth2:
    client:
      access-token-uri: http://localhost:9004/oauth/token
      user-authorization-uri: http://localhost:9004/oauth/authorize

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
