server:
  port: 10001


security:
  oauth2:
    client:
      access-token-uri: http://localhost:9004/oauth/check_token
    authorization:
      check-token-access: http://localhost:9004/oauth/check_token

